<?php
/**
 * Processor: Trigger autonewsletter scheduling
 *
 * Allows manual trigger of the autonewsletter schedule
 * Script will output a list of upcoming newsletters generated by a autonewsletter to be scheduled
 * For testing purposes mostly
 */
// var_dump($_POST);

$modx->campaigner->sheduleAutoNewsletter($_POST['id']);

return $modx->error->success();